[package]
name = "sharesight-reqwest"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
sharesight-types = { path = "../sharesight-types" }
thiserror = "1.0"
